services:
  app:
    container_name: yourl
    image: yourls:1.9.2-apache
    restart: unless-stopped
    user: www-data:www-data
    networks:
      - public
    env_file:
      - ./app.env
    volumes:
      - ./index.php:/var/www/html/index.php

networks:
  public:
    external: true

