services:
  app:
    container_name: yourls
    image: yourls:1.10.1-apache
    restart: unless-stopped
    user: www-data:www-data
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - ./index.php:/var/www/html/index.php

networks:
  default:
    name: web
    external: true

