services:
  yourls:
    image: yourls:1.9.2-fpm-alpine
    container_name: yourls
    user: www-data:www-data
    restart: unless-stopped
    networks:
      - public
    env_file:
      - ./app.env
    volumes:
      - ./index.php:/var/www/html/index.php

networks:
  public:
    external: true

