services:
  app:
    image: yourls:1.9.2-fpm-alpine
    user: www-data:www-data
    networks:
      - public
    environment:
      - YOURLS_SITE=https://url.muflone.com
      - YOURLS_PRIVATE=true

networks:
  public:
    external: true

