services:
  app:
    image: yourls:1.9.2-apache
    container_name: yourl
    restart: unless-stopped
    user: www-data:www-data
    networks:
      - public
    env_file:
      - ./app.env

networks:
  public:
    external: true

